# Site
name: 'SMB 2020'
description: 'The Society for Mathematical Biology - e-Conference 2020.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/2020'
url:     "https://smbarchive.github.io"
disqus: 'smb2020'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sandy:
      name:           "Sandy Anderson"
      avatar:         assets/images/logo.jpg
      bio:            "President of Society for Mathematical Biology"
      twitter:        https://twitter.com/ara_anderson
      
    esmb:
      name:           "eSMB2020"
      site:           https://www.smb2020.org
      avatar:         assets/images/logo.jpg
      bio:            "Virtual conference of the Society for Mathematical Biology, 2020."
      twitter:        https://twitter.com/ESmb2020
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all abstracts
  - scope:
      path: "_abstracts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]